## NOME DA APLICACAO
spring.application.name=rental-cars-spring-api

## API REST
spring.mvc.servlet.path=/api

## AUTENTICACAO E AUTORIZACAO
## Cors
cors.allowed-origins-front=http://localhost:8080

## Tamanho do arquivo
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

## BANCO DE DADOS

# Ativar logs das instrucoes SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=DEBUG

## LOGS
logging.level.org.springframework.web=DEBUG
logging.level.com.challenge.rental_cars_spring_api=DEBUG

# Atributos da conexao
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracao do Liquibase
spring.liquibase.change-log=classpath:liquibase/changelog.xml

spring.web.resources.add-mappings=false